import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";
import {Inter} from "next/font/google"

const font = Inter({
  weight: ['400', "500", "600", "700", "800",],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-gray-100`}>
        <Providers>
          <div className="max-w-6xl mx-auto w-svw">
            {children}
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
